### PR TITLE
Fix/swap quote schema validation

### LINKED ISSUE #51: Add request params validation and throw 400 on invalid requests
About
===

Currently a `GET` request with no query parameters to https://api.0x.org/swap/quote will cause the API to return `500` with an exception:
```
{"reason":"Cannot read property 'startsWith' of undefined"}
```

It would be best to add query parameter validation, and throw `400` with a helpful message back to the requester specifying missing / invalid parameters.

### PR DESCRIPTION
**Pull request by dekz**
Had to do more of a roundabout schema to avoid a generic `is not any of [subschema 0],[subschema 1]`. This can still occur with `/wholeNumberSchema`.

The typings also do not seem to allow this schema, so `as any` is required for now.

Resolves #51

### CODE REVIEW

File: src/utils/schema_utils.ts [hunk 1]
```diff
@@ -9,47 +8,44 @@ const schemaValidator = new SchemaValidator();
...
-                validationResult.errors,
-                (schemaValidationError: SchemaValidationError) =>
-                    schemaValidationErrorToValidationErrorItem(schemaValidationError),
+            const validationErrorItems = validationResult.errors.map((schemaValidationError: SchemaValidationError) =>
+                schemaValidationErrorToValidationErrorItem(schemaValidationError),
             );
             throw new ValidationError(validationErrorItems);
         }
     },
+    addSchema(schema: Schema): void {
```
Comment (xianny) [inline src/utils/schema_utils.ts]: curious, what does this do?

File: src/schemas/swap_quote_request_schema.json [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+    "id": "/SwapQuoteRequestSchema",
+    "properties": {
+        "sellToken": {
+            "type": "string"
+        },
+        "buyToken": {
+            "type": "string"
+        },
+        "takerAddress": {
+            "$ref": "/addressSchema"
```
Comment (xianny) [inline src/schemas/swap_quote_request_schema.json]: does the `addSchema` thing allow us to reference `/addressSchema`'s relative path from `json-schemas`?

Comment (dekz) [reply src/schemas/swap_quote_request_schema.json]: Yes exactly, unused now, probably needed in the future. There was an open question on "how this is done".
